export default [
  {
    "id":698,
    "image":
      {
        "url":"https://s3.amazonaws.com/wll-community-production/images/no-avatar.png"
      },
    "full_name":"Andrey Ivanov",
    "country":null,
    "languages":[],
    "experience":null,
    "availability":null,
    "place_to_work":null,
    "price":1231,
    "profession":null,
    "skill_tags":[],
    "promotions":
      [
        {
          "id":33,
          "title":"Web, Mobile \u0026 Software Dev",
          "description":"Any skill test defined by the client",
          "created_at":"2016-10-11T07:21:53.797Z",
          "updated_at":"2016-11-01T06:38:29.778Z",
          "promotion_type":"default",
          "profession_category_id":1
        },
        {
          "id":34,
          "title":"Web, Mobile \u0026 Software Dev",
          "description":"Make 1 HTML page from PSD file for free ",
          "created_at":"2016-10-11T07:21:53.800Z",
          "updated_at":"2016-11-01T06:38:29.783Z",
          "promotion_type":"default",
          "profession_category_id":1
        }
      ],
    "last_seen_at":"2019-01-28T06:42:33.683Z",
    "offers":[],
    "total_rate":0.0,
    "owner":false,
    "favorited":false,
    "saved_count":0,
    "media":
      {
        "files":[],
        "audio":[],
        "images":[]
      },
    "total_jobs":1,
    "total_hours":0
  },
  {
    "id":673,
    "image":
      {
        "url":"https://tallents.s3-us-west-2.amazonaws.com/uploads/avatars/277de776a29e5ace1aba82af4298c8743719019b/blob?X-Amz-Expires=600\u0026X-Amz-Date=20190128T065639Z\u0026X-Amz-Algorithm=AWS4-HMAC-SHA256\u0026X-Amz-Credential=AKIAJ75H3M6JY2F6TKYA/20190128/us-west-2/s3/aws4_request\u0026X-Amz-SignedHeaders=host\u0026X-Amz-Signature=272fc9e8669bdf581542a51f4e89b81f42a6c42891ba5f0ee5a011e3e7a28740"
      },
    "full_name":"clint eastwood",
    "country":null,
    "languages":[],
    "experience":null,
    "availability":null,
    "place_to_work":null,
    "price":null,
    "profession":null,
    "skill_tags":[],
    "promotions":[],
    "last_seen_at":"2019-01-28T06:56:17.296Z",
    "offers":[],
    "total_rate":0.0,
    "owner":false,
    "favorited":false,
    "saved_count":1,
    "media":
      {
        "files":[],
        "audio":[],
        "images":[]
      },
    "total_jobs":0,
    "total_hours":0
  },
  {
    "id":669,
    "image":{"url":"https://s3.amazonaws.com/wll-community-production/images/no-avatar.png"},
    "full_name":"dsfsdfsdf sdfsfsdf",
    "country":null,
    "languages":[],
    "experience":null,
    "availability":null,
    "place_to_work":null,
    "price":null,
    "profession":null,
    "skill_tags":
      [
        {
          "id":191,
          "name":"ArchiCAD",
          "created_at":"2016-09-23T14:24:10.288Z",
          "updated_at":"2016-09-23T14:24:10.288Z"
        }
      ],
    "promotions":[],
    "last_seen_at":"2019-01-11T06:17:43.094Z",
    "offers":[],
    "total_rate":0.0,
    "owner":false,
    "favorited":false,
    "saved_count":1,
    "media":
      {
        "files":[],
        "audio":[],
        "images":[]
      },
    "total_jobs":0,
    "total_hours":0
  },
  {
    "id":663,
    "image":{"url":"https://s3.amazonaws.com/wll-community-production/images/no-avatar.png"},
    "full_name":"olegoleg olegoleg",
    "country":null,
    "languages":[],
    "experience":null,
    "availability":null,
    "place_to_work":null,
    "price":null,
    "profession":null,
    "skill_tags":[],
    "promotions":[],
    "last_seen_at":"2019-01-13T08:06:14.154Z",
    "offers":[],
    "total_rate":0.0,
    "owner":false,
    "favorited":false,
    "saved_count":0,
    "media":
      {
        "files":[],
        "audio":[],
        "images":[]
      },
    "total_jobs":2,
    "total_hours":0
  }
]