export default [
  {
    categories: [
      {
        id: 1, 
        name: "Web, Mobile & Software Dev", 
        selected: true,
        skill_categories: [
          {
            id: 8, 
            name: "Web Development", 
            selected: true
          }
        ],
      }
    ],
    commitment: "decide_later",
    contract_general_notes: null,
    created_at: "2019-01-24T06:41:44.978Z",
    description: "2344",
    have_bid: false,
    hourly_price: 23,
    id: 701,
    level: "intern",
    offers: [],
    owner: true,
    payment: null,
    period: 1,
    period_type: "day",
    price: 230,
    privacy: "public_job",
    promotion_description: "Make 1 HTML page from PSD file for free ",
    promotion_title: "Web, Mobile & Software Dev",
    skill_tags: [],
    status: 0,
    time_type: "short",
    title: "create landing",
    user: {
      address: null,
      availability: null,
      city: null,
      country: null,
      cover_letter: null,
      date_of_birthday: null,
      email: "ivanov.a.e@icloud.com",
      experience: null,
      favorited: false,
      first_name: "Andrey",
      full_name: "Andrey Ivanov",
      id: 698,
      image: {
        url: "https://s3.amazonaws.com/wll-community-production/images/no-avatar.png",
      },
      image_original: {
        url: "https://s3.amazonaws.com/wll-community-production/images/no-avatar.png"
      },
      languages: [],
      last_seen_at: "2019-01-25T10:54:58.899Z",
      media: {
        files: [], 
        audio: [], 
        images: []
      },
      mobile: null,
      place_to_work: null,
      price: 1231,
      profession: null,
      saved_count: 0,
      skill_test_send: 0,
      total_jobs: 1,
      total_rate: 0,
      zipcode: null,
    },
  },
  {
    categories: false,
    commitment: "per_week_up_to_30",
    contract_general_notes: null,
    created_at: "2019-01-22T06:07:31.368Z",
    description: "1",
    have_bid: false,
    hourly_price: null,
    id: 700,
    level: "expert",
    offers: [],
    owner: false,
    payment: null,
    period: 1,
    period_type: "day",
    price: 1,
    privacy: "public_job",
    promotion_description: "Any skill test defined by the client",
    promotion_title: "Web, Mobile & Software Dev",
    skill_tags: [],
    status: 0,
    time_type: null,
    title: "1",
    user: {
      address: null,
      availability: null,
      city: null,
      country: null,
      cover_letter: null,
      date_of_birthday: null,
      email: "1@mail.ru",
      experience: null,
      favorited: false,
      first_name: "1234",
      full_name: "1234 1234",
      id: 664,
      image: {
        url: "https://s3.amazonaws.com/wll-community-production/images/no-avatar.png",
      },
      image_original: {
        url: "https://s3.amazonaws.com/wll-community-production/images/no-avatar.png"
      },
      languages: [],
      last_seen_at: "2019-01-25T11:03:30.423Z",
      media: {files: [], audio: [], images: []},
      mobile: null,
      place_to_work: null,
      price: null,
      profession: null,
      saved_count: 0,
      skill_test_send: 0,
      total_jobs: 5,
      total_rate: 0,
      zipcode: null,
    },
  },
  {
    categories: false,
    commitment: "decide_later",
    contract_general_notes: "qwerasdf qwerasdf zxcvasdfqwer vbnmghjrtyu asdfqwerrtyu",
    created_at: "2019-01-22T05:51:44.538Z",
    description: "description 1q2w3e4r5t6y",
    have_bid: false,
    hourly_price: null,
    id: 699,
    level: "expert",
    offers: [],
    owner: false,
    payment: null,
    period: 2,
    period_type: "month",
    price: 10000,
    privacy: "public_job",
    promotion_description: "Any skill test defined by the client",
    promotion_title: "Web, Mobile & Software Dev",
    skill_tags: [],
    status: 0,
    time_type: "one_time",
    title: "1q2w3e4r5t6y",
    user: {
      address: null,
      availability: null,
      city: null,
      country: null,
      cover_letter: null,
      date_of_birthday: null,
      email: "1@mail.ru",
      experience: null,
      favorited: false,
      first_name: "1234",
      full_name: "1234 1234",
      id: 664,
      image: {
        url: "https://s3.amazonaws.com/wll-community-production/images/no-avatar.png",
      },
      image_original: {
        url: "https://s3.amazonaws.com/wll-community-production/images/no-avatar.png",
      },
      languages: [],
      last_seen_at: "2019-01-25T11:03:30.423Z",
      media: {files: [], audio: [], images: []},
      mobile: null,
      place_to_work: null,
      price: null,
      profession: null,
      saved_count: 0,
      skill_test_send: 0,
      total_jobs: 5,
      total_rate: 0,
      zipcode: null,
    },
  },
  {
    categories: false,
    commitment: "per_week_10",
    contract_general_notes: "Контрактные генеральные ноты",
    created_at: "2019-01-22T05:15:49.088Z",
    description: "Описание тестовой работы",
    have_bid: false,
    hourly_price: 9988,
    id: 698,
    level: "junior",
    offers: [],
    owner: false,
    payment: null,
    period: 1,
    period_type: "day",
    price: 9988,
    privacy: "public_job",
    promotion_description: "Any skill test defined by the client",
    promotion_title: "Accounting & Consulting",
    skill_tags: [],
    status: 0,
    time_type: "short",
    title: "Тестовая работа",
    user: {
      address: null,
      availability: null,
      city: null,
      country: null,
      cover_letter: null,
      date_of_birthday: null,
      email: "1@mail.ru",
      experience: null,
      favorited: false,
      first_name: "1234",
      full_name: "1234 1234",
      id: 664,
      image: {
        url: "https://s3.amazonaws.com/wll-community-production/images/no-avatar.png",
      },
      image_original: {
        url: "https://s3.amazonaws.com/wll-community-production/images/no-avatar.png",
      },
      languages: [],
      last_seen_at: "2019-01-25T11:03:30.423Z",
      media: {files: [], audio: [], images: []},
      mobile: null,
      place_to_work: null,
      price: null,
      profession: null,
      saved_count: 0,
      skill_test_send: 0,
      total_jobs: 5,
      total_rate: 0,
      zipcode: null,
    },
  },
]