export const SHOW_MODAL_REGISTRATION = 'SHOW_MODAL_REGISTRATION';
export const CLOSE_MODAL_REGISTRATION = 'CLOSE_MODAL_REGISTRATION';
export const SHOW_MODAL_LOGIN = 'SHOW_MODAL_LOGIN';
export const CLOSE_MODAL_LOGIN = 'CLOSE_MODAL_LOGIN';
export const ADD_NEW_USER = 'ADD_NEW_USER';
export const GET_ID_JOB = 'GET_ID_JOB';